# free_providers.py — Master Free AI Providers Registry
# ALP = Allowance Preservation. AAFL = AI Agent Feedback Loop.

PROVIDERS = {
    "cerebras": {
        "base_url": "https://api.cerebras.ai/v1",
        "api_key_env": "CEREBRAS_API_KEY",
        "models": ["llama-3.3-70b", "qwen3-32b", "qwen3-235b", "gpt-oss-120b"],
        "free_tokens_per_day": 1000000,
        "free_rpm": 30,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "speed",
        "signup": "https://cloud.cerebras.ai",
    },
    "groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "api_key_env": "GROQ_API_KEY",
        "models": ["llama-3.3-70b-versatile", "llama-3.3-8b-instant", "deepseek-r1-distill-llama-70b"],
        "free_requests_per_day": 1000,
        "free_rpm": 30,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "fast_text",
        "signup": "https://console.groq.com",
    },
    "gemini": {
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_key_env": "GEMINI_API_KEY",
        "models": ["gemini-2.5-flash", "gemini-2.5-pro"],
        "free_requests_per_day": 1500,
        "free_rpm": 15,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "vision_and_reasoning",
        "signup": "https://aistudio.google.com/apikey",
    },
    "mistral": {
        "base_url": "https://api.mistral.ai/v1",
        "api_key_env": "MISTRAL_API_KEY",
        "models": ["mistral-small-3.1", "codestral-latest", "mistral-embed"],
        "free_tokens_per_month": 1000000000,
        "free_rpm": 2,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "code_and_batch",
        "signup": "https://console.mistral.ai",
    },
    "openrouter": {
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "models": ["openrouter/auto", "openai/gpt-oss-20b:free", "meta-llama/llama-3.3-70b-instruct:free"],
        "free_requests_per_day": 50,
        "free_rpm": 20,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "fallback_gateway",
        "signup": "https://openrouter.ai",
    },
    "lmstudio": {
        "base_url": "http://127.0.0.1:1234/v1",
        "api_key_env": None,
        "models": ["qwen2.5-coder-32b-instruct", "qwen2.5-vl-32b-instruct", "deepseek-r1-70b", "phi-4-14b"],
        "free_requests_per_day": None,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "local_primary",
    },
    "huggingface": {
        "base_url": "https://api-inference.huggingface.co/models",
        "api_key_env": "HF_API_KEY",
        "models": ["meta-llama/Llama-3.2-11B-Vision-Instruct"],
        "free_rpm": 5,
        "cost_per_call": 0.0,
        "permanent_free": True,
        "aafl_role": "specialist_niche",
        "signup": "https://huggingface.co",
    },
    "cohere": {
        "base_url": "https://api.cohere.com/v1",
        "api_key_env": "COHERE_API_KEY",
        "models": [
